name: Github Pages
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Install Bundler
        run: gem install bundler

      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: "github"
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ""
          branch: "gh-pages"
          jekyll_src: "./"
          jekyll_cfg: "_config.yml"
          jekyll_baseurl: "/jekyll-theme-yat"
          cname: ""
          actor: ""
