name: Github Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1" # 또는 더 최신 버전
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build and Deploy
        uses: jeffreytse/jekyll-deploy-action@v0.5.1
        with:
          provider: "github"
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ""
          branch: "gh-pages"
          jekyll_src: "./"
          jekyll_cfg: "_config.yml"
          jekyll_baseurl: "/jekyll-theme-yat"
          cname: ""
          actor: ""
